config/routes.rb
BandTrack::Application.routes.draw do
  devise_for :users
  resources :exercises

  resources :routines

  resources :logs

  post '/steps' => 'steps#create'
  delete '/steps/:id' => 'steps#destroy', as: :destroy_step

  root 'pages#start'
  get '/about' => 'pages#about'


end

app/models/routine.rb
class Routine < ActiveRecord::Base

  belongs_to :user
  has_many :steps, dependent: :destroy
  has_many :exercises, through: :steps

  validates :routine_name, presence: true
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :set_routine, only: [:show, :edit, :update, :destroy]

 before_action :ensure_user_is_current_user, only: [:destroy]

  def ensure_user_is_current_user
    unless current_user == @user
      redirect_to :back, alert: "Unauthorized area"
    end
  end

  # GET /routines
  # GET /routines.json
  def index
    @routines = Routine.all
  end

  # GET /routines/1
  # GET /routines/1.json
  def show
  end

  # GET /routines/new
  def new
    @routine = Routine.new
  end

  # GET /routines/1/edit
  def edit
  end

  # POST /routines
  # POST /routines.json
  def create
    @routine = Routine.new(routine_params)

    respond_to do |format|
      if @routine.save
        format.html { redirect_to @routine, notice: 'Routine was successfully created.' }
        format.json { render action: 'show', status: :created, location: @routine }
      else
        format.html { render action: 'new' }
        format.json { render json: @routine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routines/1
  # PATCH/PUT /routines/1.json
  def update
    respond_to do |format|
      if @routine.update(routine_params)
        format.html { redirect_to @routine, notice: 'Routine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @routine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routines/1
  # DELETE /routines/1.json
  def destroy
    @routine.destroy
    respond_to do |format|
      format.html { redirect_to routines_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_routine
      @routine = Routine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def routine_params
      params.require(:routine).permit(:routine_name)
    end
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/views/routines/_form.html.erb
<%= form_for(@routine) do |f| %>
  <% if @routine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@routine.errors.count, "error") %> prohibited this routine from being saved:</h2>

      <ul>
      <% @routine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :routine_name %><br>
    <%= f.text_field :routine_name %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/routines/edit.html.erb
<h1>Editing <%= @routine.routine_name %></h1>


<%= form_tag routine_url(@routine.id), :method => 'patch' do %>
  <%= label_tag :routine_id %>
  <%= text_field_tag :routine_id, @routine.routine_name %>
  <%= submit_tag %>
  <% end %>

<div class = 'row'>
  <% @routine.steps.each do |step|%>
   <%= link_to step.exercise.image, exercise_url(step.exercise) %>
    <%= link_to "Delete?", destroy_step_url(step.id), method: :delete %></div>
  <% end %>


<h2>Add exercise</h2>
  <%= form_tag steps_url, :method => 'post' do %>
    <%= hidden_field_tag :routine_id, @routine.id %>
    <%= label_tag :exercise_id %>
    <%= select_tag :exercise_id, options_from_collection_for_select(Exercise.all, :id, :ex_name) %>
    <%= submit_tag %>
  <% end %>

<%= link_to 'Show', @routine %> |
<%= link_to 'Back', routines_path %>

app/views/routines/index.html.erb
<h1><%= current_user.email %> routines</h1>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Panel title</h3>
  </div>
  <div class="panel-body">
    Panel content
  </div>
</div>

   <% @routines.each do |routine| %>
<div class "panel panel-primary">
  <div class="panel-heading">
      <h3 class="panel-title"><%= link_to routine.routine_name, routine %></h3>
  </div>
  <div class="panel-body">
        <%= link_to 'Edit Routine', edit_routine_path(routine) %> | <%= link_to 'Delete routine', routine, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>
        <% end %>

<br>

<h4><%= link_to 'Create a New Routine', new_routine_path %></h4>

app/views/routines/new.html.erb
<h1>New routine</h1>

<%= render 'form' %>

<%= link_to 'Back', routines_path %>

app/views/routines/show.html.erb
<p id="notice"><%= notice %></p>

<div class = 'jumbotron routine-head'>

  <h1><strong>Routine name:</strong>
  <%= @routine.routine_name %></h1>

  <h4><%= link_to 'Log my exercise', new_log_url %></h4>
</div>

<div class = 'row'>
  <% @routine.exercises.each do |exercise|%>
    <div class = 'col-md-3'><%= link_to exercise.image, exercise_url %></div>

  <% end %>
</div>

<br>
<%= link_to "Add an Exercise to this routine", edit_routine_url %>
<br>


<%= link_to 'Edit routine', edit_routine_path(@routine) %> |
<%= link_to 'See all routines', routines_path %>