config/routes.rb
BandTrack::Application.routes.draw do
  devise_for :users
  resources :exercises

  resources :routines

  resources :logs

  post '/steps' => 'steps#create'
  delete '/steps/:id' => 'steps#destroy', as: :destroy_step

  root 'pages#start'
  get '/about' => 'pages#about'


end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :exercise

end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]

  before_action :ensure_user_is_current_user, only: [:edit, :update, :destroy]
  #probably want to make this for all log actions

  def ensure_user_is_current_user
    unless current_user == @user
      redirect_to :back, alert: "Unauthorized area"
    end
  end

  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.all
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
  end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render action: 'show', status: :created, location: @log }
      else
        format.html { render action: 'new' }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      params.require(:log).permit(:sets, :reps, :user_id, :exercise_id)
    end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= form_for(@log) do |f| %>
  <% if @log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% @log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sets %><br>
    <%= f.number_field :sets %>
  </div>
  <div class="field">
    <%= f.label :reps %><br>
    <%= f.number_field :reps %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :exercise_id %><br>
    <%= f.number_field :exercise_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing log</h1>

<%= render 'form' %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<h1>Listing logs</h1>
<!-- each routine should click open with javascript and show the exercises and ability to log -->
<table>
  <thead>
    <tr>
      <th>Routine</th>
      <th>Exercise</th>
      <th>Sets</th>
      <th>Reps</th>

      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.exercise_id %></td>
        <td><%= log.sets %></td>
        <td><%= log.reps %></td>

        <td><%= link_to 'Show', log %></td>
        <td><%= link_to 'Edit', edit_log_path(log) %></td>
        <td><%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Log', new_log_path %>

app/views/logs/new.html.erb
<h1>New log</h1>

<%= render 'form' %>

<%= link_to 'Back', logs_path %>

# need to pass information from routine if clicked over from there to know which routine is being logged
#use form for for each exercise, which is a row in a table?
   <%= form_tag logs_url, :method => 'post' do %>
                <%= hidden_field_tag :exercise_id, @exercise.id %>
                <%= label_tag :bandcolor %>
                <%= select_tag :bandcolor, options_from_collection_for_select(Log.all, :id, :bandcolor) %>
                <%= submit_tag %>
              <% end %>
<div class = 'row routine'>
  <div class = 'col-md-3'> Exercise </div>
  <div class = 'col-md-3'> Band Color </div>
  <div class = 'col-md-3'> Sets </div>
  <div class = 'col-md-3'> Reps </div>
</div>

              <div class = 'row'>
  <% @routine.exercises.each do |exercise|%>
    <div class = 'col-md-3'><%= link_to exercise.ex_name, exercise_url %></div>
    <div class = 'col-md-3'>
      <div class = 'btn-grp'>
        <button type = 'button' class = 'btn btn-default dropdown-toggle' data-toggle='dropdown'>Band color
        </button>
        <ul class="dropdown-menu" role="menu">
          <li>Tan</li>
          <li>Yellow</li>
          <li>Red</li>
          <li>Green</li>
          <li>Blue</li>
          <li>Black</li>
          <li>Silver</li>
          <li>Gold</li>
        </ul>
      </div>
    </div>
    <div class = 'col-md-3'> sets </div>
    <div class = 'col-md-3'> reps </div>
  <% end %>
</div>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Routine:</strong>
  <%= @log.routine_id %>
</p>

<p>
  <strong>Exercise:</strong>
  <%= @log.exercise_id %>
</p>

<p>
  <strong>Sets:</strong>
  <%= @log.sets %>
</p>

<p>
  <strong>Reps:</strong>
  <%= @log.reps %>
</p>


<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>