config/routes.rb
BandTrack::Application.routes.draw do
  devise_for :users
  resources :exercises

  resources :routines

  resources :logs

  post '/steps' => 'steps#create'
  delete '/steps/:id' => 'steps#destroy', as: :destroy_step

  root 'pages#start'
  get '/about' => 'pages#about'


end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  before_action :ensure_user_is_admin, only: [:edit, :update, :destroy, :create]


  def ensure_user_is_admin
    unless current_user.admin == true
      redirect_to :back, alert: "Unauthorized area"
    end
  end


  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.all
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render action: 'show', status: :created, location: @exercise }
      else
        format.html { render action: 'new' }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_params
      params.require(:exercise).permit(:ex_name, :description, :tip, :image)
    end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ex_name %><br>
    <%= f.text_field :ex_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :tip %><br>
    <%= f.text_field :tip %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing exercise</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<h1>Listing exercises</h1>

<table>
  <thead>
    <tr>
      <th>Ex name</th>
      <th>Description</th>
      <th>Tip</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @exercises.each do |exercise| %>
      <tr>
        <td><%= exercise.ex_name %></td>
        <td><%= exercise.description %></td>
        <td><%= exercise.tip %></td>
        <td><%= exercise.image %></td>
        <td><%= link_to 'Show', exercise %></td>

        <td>
        <%= form_tag steps_url, :method => 'post' do %>
           <%= hidden_field_tag :exercise_id, exercise.id %>
            <%= label_tag 'Add to routine' %>
            <%= select_tag :routine_id, options_from_collection_for_select(Routine.all, :id, :routine_name) %>
          <%= submit_tag 'Save to routine'%>
          <% end %>
          </td>
         <!-- add if current user = admin code here -->
        <td><%= link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exercise', new_exercise_path %>

app/views/exercises/new.html.erb
<h1>New exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ex name:</strong>
  <%= @exercise.ex_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @exercise.description %>
</p>

<p>
  <strong>Tip:</strong>
  <%= @exercise.tip %>
</p>

<p>
  <strong>Image:</strong>
  <%= @exercise.image %>
</p>
<%= link_to 'Add to routine', routines_url %>
<br>
<%= link_to 'See all exercises', exercises_path %>